LEVEL = ../..
LEX = flex
YACC = bison
YFLAGS = -d
TOOLNAME = lvaluec
LINK_COMPONENTS := all engine jit interpreter nativecodegen
REQUIRES_RTTI := 1
USEDLIBS = lvaluel.a

include $(LEVEL)/Makefile.common
